# Generated by Django 2.2 on 2022-01-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_category_course_image_instructor_review_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_path',
            field=models.CharField(max_length=255),
        ),
    ]
