# Generated by Django 2.2 on 2022-01-08 22:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20220108_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_path',
        ),
        migrations.AddField(
            model_name='image',
            name='images_path',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/<django.db.models.fields.related.ForeignKey>/images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='video_path',
            field=models.FileField(upload_to='uploads/<django.db.models.fields.related.ForeignKey>/videos/'),
        ),
    ]
