# Generated by Django 2.2 on 2022-01-08 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_auto_20220108_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='images_path',
        ),
        migrations.AddField(
            model_name='image',
            name='image_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='video_path',
            field=models.CharField(max_length=255),
        ),
    ]
