# Generated by Django 2.2 on 2022-01-13 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='statuc_text',
            new_name='status_text',
        ),
    ]
